services:
  - type: web
    name: my-n8n-render
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_URL
        value: https://sanjaymn8n-5o4y.onrender.com/
      - key: N8N_USER_FOLDER
        value: /home/node/.n8n
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
